openapi: "3.0.3"
info:
  title: Server
  version: "1.0"
servers:
  - url: http://localhost:3000/
tags:
  - name: IceBreakers
    description: IceBreakers APIs
paths:
  /api/p/icebreaker:
    $ref: "./icebreakers.yaml#/paths/~1icebreakers"
