openapi: "3.0.3"
info:
  title: Server
  version: "1.0"
servers:
  - url: http://localhost:3000/
tags:
  - name: Users
    description: Users APIs
paths:
  /api/p/users/{id}:
    $ref: "./users.yaml#/paths/~1users~1{id}"
  /api/p/users:
    $ref: "./users.yaml#/paths/~1users"
